#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "--------------------------------------------------"
  echo "ERROR!!!! You can't commit directly to main branch"
  echo "--------------------------------------------------"
  exit 1
fi
yarn testReport
